# Generated by Django 3.2.18 on 2023-07-09 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_timesstap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='timesstap',
            new_name='timestamp',
        ),
    ]
